spring.application.name=MultiModuleAIChatApplication

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2

# OpenAI (optional)
spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key}
spring.ai.openai.base-url=https://api.openai.com/v1
spring.ai.openai.chat.options.model=gpt-4o-mini

#spring.ai.chat.client.enabled = false