spring.application.name=practice
spring.ai.model.chat = ollama
spring.ai.ollama.chat.model = llama3.2

#spring.ai.openai.api-key = <your openai api key>
#[optional] spring.ai.openai.base-url = https://api.openai.com/v1
#[optional] spring.ai.openai.chat.options.model = gpt-4o-mini

logging.level.org.springframework.ai=DEBUG
#logging.level.org.springframework.ai.openai=DEBUG
logging.level.org.springframework.ai.ollama=DEBUG

# I have added below section to support JDBC backed Chat memory

# --- H2 Database (file-based) ---
spring.datasource.url=jdbc:h2:file:C:/data/chatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# --- Enable H2 Console (optional for debugging) ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Initialize schema from SQL --- to support H2 DB
# --- normally AI chat memory does not support H2 DB --- no such file like schema-oracle.sql
## spring.sql.init.mode=always --initially then change it to never
spring.sql.init.mode=never
spring.sql.init.platform=h2
spring.sql.init.schema-locations=classpath:sql/schema-h2.sql

# --- Spring AI Chat Memory JDBC Store ---
#spring.ai.memory.store.type=jdbc
#--- spring.docker.compose.stop.command=stop will keep the data stored
spring.docker.compose.stop.command=down
# --------- qdrant Database ---------
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=ragTest
