spring.application.name=mcp
spring.ai.model.chat = ollama
spring.ai.ollama.chat.model = llama3.2

# Enable MCP client - optional
spring.ai.mcp.client.enabled=true

# Use stdio transport and point to your server config
spring.ai.mcp.client.stdio.servers-configuration=classpath:/mcp-server.json